### ISSUE TITLE
Server files are unwriteable in rootless mode

### ISSUE THREAD

**Issue by TippyLion28** [mtoensing/Docker-Minecraft-PaperMC-Server#102]
Hi,

My compose file looks like this:

```yml
version: '3'

services:
  mcserver:
    image: marctv/minecraft-papermc-server:1.20
    container_name: mcserver
    environment:
      - MEMORYSIZE=1G
      - PUID=1000
      - PGID=1000
    volumes:
      - ./server:/data:rw
    ports:
      - "25565:25565"
    stdin_open: true
    tty: true
    restart: unless-stopped
```

I am running the container in rootless mode. The server files get created under a UID of 100999:

```text
$ ls -la
total 44
drwxr-xr-x  9 100999 100999 4096 Dec 17 14:37 .
drwxr-xr-x  3 scott  109000 4096 Dec 17 14:37 ..
drwxr-xr-x  2 100999 100999 4096 Dec 17 14:37 cache
drwxr-xr-x  2 100999 100999 4096 Dec 17 14:37 config
-rw-r--r--  1 100999 100999  158 Dec 17 14:37 eula.txt
drwxr-xr-x 11 100999 100999 4096 Dec 17 14:37 libraries
drwxr-xr-x  2 100999 100999 4096 Dec 17 14:37 logs
drwxr-xr-x  2 100999 100999 4096 Dec 17 14:37 plugins
-rw-r--r--  1 100999 100999 1297 Dec 17 14:37 server.properties
drwxr-xr-x  3 100999 100999 4096 Dec 17 14:37 versions
drwxr-xr-x  3 100999 100999 4096 Dec 17 14:37 world
```

I can't write to these files without root. Is this expected? Am I doing something wrong? Hope somebody can help me here :)

Really nice project! Makes setting up papermc servers so fast and simple especially with compose :)))
