### ISSUE TITLE
Changing the port for hosting multiple servers

### ISSUE THREAD

**Issue by joelbattig** [mtoensing/Docker-Minecraft-PaperMC-Server#121]
Hi, maybe Im stupid but as far as I can tell there's no option to change the server port for hosting multiple servers? changing the port in the yaml file has no effect on the config. Is there already a way to do this from the config?

**Comment by b2un0** [comment]
a change of the outgoing port should be work:
eg
```yaml
services:
  mcserver-1:
    image: docker.io/marctv/minecraft-papermc-server:latest
    restart: always
    container_name: "mcserver-1"
    volumes:
      - "/home/pi/mcserver1:/data:rw"
    ports:
      - "25565:25565"
    stdin_open: true
    tty: true

  mcserver-2:
    image: docker.io/marctv/minecraft-papermc-server:latest
    restart: always
    container_name: "mcserver-2"
    volumes:
      - "/home/pi/mcserver2:/data:rw"
    ports:
      - "25566:25565" # 25566 is the new port
    stdin_open: true
    tty: true
```
