### ISSUE TITLE
Can't use PUID and GUID

### ISSUE THREAD

**Issue by MariusROBERT** [mtoensing/Docker-Minecraft-PaperMC-Server#122]
I tried to setup a minecraft server as non root by providing my PUID and GUID (1000:1000 obtained with `id -p $user` and `id -g $user`) but when I start the docker, I get these logs 
```
First start of the docker container, start initialization process.
Starting with 1000:1000 (UID:GID)
fatal: The GID `1000' is already in use.
```
here's my whole docker-compose
```
version: "3"

services:
  minecraft:
    image: marctv/minecraft-papermc-server:1.21-111
    restart: always
    container_name: "mcserver"
    environment:
      - MEMORYSIZE=1G
      - PAPERMC_FLAGS=""
      - PUID=1000
      - PGID=1000
    volumes:
      - ./minecraft:/data
    ports:
      - "25565:25565"
```
I tried to remove the `PUID` and `GUID` lines in the docker-compose but it change the ownership of my files and I'd prefer to avoir running my container as root

I tried adding `SKIP_PERM_CHECK=true` in the env vars but I get a lot of java `permission denied` error at the server startup resulting in a final crash with red errors
```
[08:48:44 ERROR]: Failed to start the minecraft server
java.nio.file.AccessDeniedException: ./world/session.lock
[...]
```
I can provide the whole java logs error logs if needed
