### ISSUE TITLE
Docker HEALTHCHECK

### ISSUE THREAD

**Issue by Rycochet** [mtoensing/Docker-Minecraft-PaperMC-Server#124]
Just a quick suggestion to add a Docker HEALTHCHECK, either in the readme for the docker compose example, or actually within the Dockerfile itself.

<https://docs.docker.com/reference/dockerfile/#healthcheck>

The actual command that works for checking if the server itself is up and running (and allowing connections is - `bash -c 'cat < /dev/null > /dev/tcp/localhost/25565'` - we're cheating a little as netcat isn't installed, but basically it tries to open a connection using bash, if that fails it will wait until the system connection timeout, so adding a 5s timeout option (the default is 30s) - it should be near instant or not at all

For my docker compose I use -

```yaml
services:
  minecraft:
    # ...
    healthcheck:
      timeout: "5s"
      start_period: "5m" # Long enough for download and build etc
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/25565'"
```

For the Dockerfile it'd be something like -

```
HEALTHCHECK --timeout=5s --start-period=5m CMD "bash -c 'cat < /dev/null > /dev/tcp/localhost/25565'"
```
