### ISSUE TITLE
error: failed switching to "dockeruser:dockergroup": unable to find group dockergroup: no matching entries in group file

### ISSUE THREAD

**Issue by programatix** [mtoensing/Docker-Minecraft-PaperMC-Server#129]
Hi,

I have a docker-compose as so,
```
version: "3"
services:
  minecraft:
    image: ghcr.io/mtoensing/docker-minecraft-papermc-server:1.21.5-38
    restart: unless-stopped
    container_name: "mcserver"
    environment:
      - PUID=1234
      - PGID=100
      - MEMORYSIZE=1G
      - PAPERMC_FLAGS=
    volumes:
      - /volume1/docker/minecraftserver/data:/data
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
      - "19134:19134/tcp"
      - "19134:19134/udp"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true
```

On first build and start, it runs fine with the correct user:group. I can join the server and etc. Then if I stop and rerun, then I get the following in the log and will repeat infinitely. Currently the only method for me to restart the docker component is to perform a clean and build again.
```
running as uid : 
error: failed switching to "dockeruser:dockergroup": unable to find group dockergroup: no matching entries in group file 
running as uid : 
error: failed switching to "dockeruser:dockergroup": unable to find group dockergroup: no matching entries in group file 
```

Any idea on how to fix this? Thanks.

**Comment by programatix** [comment]
Hi,

I found the solution. New docker-compose is as such,
```
version: "3"
services:
  minecraft:
    image: ghcr.io/mtoensing/docker-minecraft-papermc-server:1.21.5-38
    restart: unless-stopped
    container_name: "mcserver"
    user: "1234:100"
    environment:
      - PUID=1234
      - PGID=100
      - MEMORYSIZE=1G
      - PAPERMC_FLAGS=
    volumes:
      - /volume1/docker/minecraftserver/data:/data
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
      - "19134:19134/tcp"
      - "19134:19134/udp"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true
```
