### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by sjal** [mtoensing/Docker-Minecraft-PaperMC-Server#3]
Hey,

Wouldn't it be a lot easier if you had docker-compose.yml prepared for using with this server? I wouldn't have to write one myself

**Comment by mtoensing** [comment]
I use this only with my synology. If you did write one I would be glad to add it to the repository.

**Comment by sjal** [comment]
Sure, I could write example line of yours and put it as a .yml for other to use

**Comment by mtoensing** [comment]
Great! Because I don't use Docker Compose for myself. If you post it here or add a pull request that would be great!

**Comment by sjal** [comment]
I didn't manage to even run the container because of some issues (KVM running on Xeon) that are apparently tied to AMD (missing . Tried debugging a bit but eventually gave up, might come back with it in a bit though. Maybe I'm not the only one with weird JVM issues like this

**Comment by mtoensing** [comment]
so there are compatibility issues with JVM if the underlying host system uses an AMD cpu? That sound weird. Many ppl use this image and I never heard of a problem like that.

**Comment by sjal** [comment]
That's what I found on the web, which is weird because I'm getting exactly the same error on a Xeon, haven't tested on AMD at all. And yeah AMD x Java is overall a global issue, requires additional flag and works flawlessly, apparently, just doesn't change a thing on my server

**Comment by mtoensing** [comment]
Show me the error then :)

**Comment by mtoensing** [comment]
Ok, let's close this for now

**Comment by leothelocust** [comment]
I know this is closed, but I needed this, so I made it.

docker-compose.yml
```yml
version: "3.9"

services:
  minecraft:
    image: "marctv/minecraft-papermc-server:1.16"
    container_name: "minecraft"
    environment: 
      MEMORYSIZE: "16G"
    volumes:
      - "/home/yourdir/minecraft:/data:rw"
    ports: 
      - "25565:25565"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true
```

and I also created a supporting Makefile (because I can never remember the docker commands)

```Makefile
help:
	@echo "Custom Makefile by Levi Olson:"; \
	echo "version 1.0"; \
	echo ""; \
	echo "\thelp\tPrints this message"; \
	echo ""; \
	echo "\tstart\tdocker-compose up --build"; \
	echo "\t\t(starts the minecraft server)"; \
	echo ""; \
	echo "\tstop\tdocker-compose stop --rmi all --remove-orphans"; \
	echo "\t\t(stops and cleans up images, but keeps data)"; \
	echo ""; \
	echo "\tattach\tdocker attach minecraft"; \
	echo "\t\t(attaches to minecraft paper jar for issuing commands)";

start:
	@echo "Starting Minecraft Server..."; \
	docker-compose up -d --build;

stop:
	@echo "Stopping Minecraft Server and cleaning up..."; \
	docker-compose down --rmi all --remove-orphans;

attach:
	@echo "Attaching to Minecraft..."; \
	echo "Ctrl-C stops minecraft and exits"; \
	echo "Ctrl-P Ctrl-Q only exits"; \
	echo ""; \
	echo "Type "help" for help."; \
	docker attach minecraft;
```

Hope this helps someone else!
